apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: objectstorages.awsblueprints.io
spec:
  group: awsblueprints.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                compositionSelector:
                  type: object
  scope: Cluster
  names:
    plural: objectstorages
    singular: objectstorage
    kind: ObjectStorage
