apiVersion: v1
kind: Service
metadata:
  name: hello-webhook-service
  namespace: hello-webhook
spec:
  type: ClusterIP
  selector:
    app: hello-webhook
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
